#!/bin/bash

if [[ -L $0 ]]; then
    BASE_DIR="$(dirname $(readlink $0))"
else
    BASE_DIR="$( cd "$( dirname "$0" )" && pwd )"
fi

# FIXME: change this to your project name
main=my-project

# change this to determine which main function will run
ns=core

cd $BASE_DIR

$BASE_DIR/node_modules/.bin/lumo -c src -m "${main}.${ns}" $@
